# Class 2_2
#### Matthew Kutugata 
#### 09-15-2019 

## Warm-Up Exercise

In [350]:
# Make a function that both prints and returns a list of the first
# n odd integers (i.e. 1, 3, 5, 7,...)

def n_odd(n):
    odd_n_list = []
    for i in range(0, n):
        odd_n_list.append(2 * i + 1)        
    return odd_n_list

In [351]:
n_odd(8)

[1, 3, 5, 7, 9, 11, 13, 15]

## Importing Packages

In [352]:
import math # math is a package

In [353]:
import math as m

In [354]:
import numpy as np # numerical python

In [355]:
x = np.arange(0, 5) # this creates a numpy array

In [356]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [357]:
# broadcasting

In [358]:
x

array([0, 1, 2, 3, 4])

In [359]:
2 * x + 1

array([1, 3, 5, 7, 9])

## Fibbonaci Number

In [360]:
# print out the first N fib #s and turn into function
# create a list of these numbers which are returned
# returns numbers below some value v

def fibo(v):
    if v <= 0: # eliminates non-output with negative numbers
            print("Error: input must be a non-zero positive number.")
    
    else: # begins fibo calculation
        fibo_list = [1]
        i = 0
        j = 1
        
        while j < v:
            fibo_list.append(j)
            i_old = i
            i = j
            j = i_old + j
            
        return fibo_list
    

In [361]:
fibo(100)

[1, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

# Practice Python
1, 2, 9, 25

## 1: Character Input
Create a program that asks the user to enter their name and their age. Print out a message addressed to them that tells them the year that they will turn 100 years old.

In [362]:
name = input("What is your name? ")
age = int(input("What is your age? "))
current_year = 2019
years_of_100 = abs((100-age) + current_year)
print(name + " you'll be 100 in " + str(years_of_100) + ".")

What is your name?  Matt
What is your age?  30


Matt you'll be 100 in 2089.


## 2: Odd or Even
Ask the user for a number. Depending on whether the number is even or odd, print out an appropriate message to the user. Hint: how does an even / odd number react differently when divided by 2?

In [363]:
user_num = int(input("Give me a number: "))
if user_num % 2 == 0:
    print("Your number is even.")
else:
    print("Your number is odd.")

Give me a number:  4


Your number is even.


## 9: Guessing Game One
Generate a random number between 1 and 9 (including 1 and 9). Ask the user to guess the number, then tell them whether they guessed too low, too high, or exactly right. (Hint: remember to use the user input lessons from the very first exercise)

In [364]:

user_num = int(input("Guess a number between 1 and 9 (including 1 and 9): "))
rando = np.random.randint(1, 10)

if user_num > 9:
    print("Error: number must be between 1 and 9 and may include 1 and 9.")
elif user_num == rando:
    print("Good guess! You got it right.")
else:
    print("Sorry, you got it wrong. I guessed " + str(rando) + ".")

    
    
    

Guess a number between 1 and 9 (including 1 and 9):  4


Sorry, you got it wrong. I guessed 2.


## 25: Guessing Game Two
In a previous exercise, we’ve written a program that “knows” a number and asks a user to guess it.

This time, we’re going to do exactly the opposite. You, the user, will have in your head a number between 0 and 100. The program will guess a number, and you, the user, will say whether it is too high, too low, or your number.

At the end of this exchange, your program should print out how many guesses it took to get your number.

As the writer of this program, you will have to choose how your program will strategically guess. A naive strategy can be to simply start the guessing at 1, and keep going (2, 3, 4, etc.) until you hit the number. But that’s not an optimal guessing strategy. An alternate strategy might be to guess 50 (right in the middle of the range), and then increase / decrease by 1 as needed. After you’ve written the program, try to find the optimal strategy! (We’ll talk about what is the optimal one next week with the solution.)

In [390]:
def guess_num():
    i = 0
    j = 100
    m = 50
    counter = 1
    
    print("Guess a number between 0 and 100")
    condition = int(input("Is your number " + str(m) + "? (press 0 for too low, 1 for correct, or 2 for too high)"))
    
    while condition != 1:
        counter += 1
        
        if condition == 0: 
            i = int(m + 1)
        elif condition == 2:
            j = int(m - 1)
        m = int((i + j) / 2)
        
        condition = int(input("Is your guess " + str(m) + "? (press 0 for too low, 1 for correct, or 2 for too high)" ))
    
    print("It took " + str(counter) + " times to guess your number.")

guess_num() 
    

Guess a number between 0 and 100


Is your number 50? (press 0 for too low, 1 for correct, or 2 for too high) 2
Is your guess 24? (press 0 for too low, 1 for correct, or 2 for too high) 1


It took 2 times to guess your number.
