make a function that prints and returns a list of the first and odd intergers 

In [1]:
x=[1,2,3,4,5,6,7,8,9]

In [2]:
print(x[::2])


[1, 3, 5, 7, 9]


the code above skips numbers to give a list of odd numbers

In [3]:
num = int(input("Enter a number: "))
mod = num % 2
if mod > 0:
    print("This is an odd number.")
else:
    print("This is an even number.")

Enter a number:  12


This is an even number.


this code allows you to enter a number and it returns an if/else print statement

In [4]:
num = int(input("Enter a number: "))
if mod > 0:
    print("This is an odd number.")
else:
    print("This is an even number.")

Enter a number:  2


This is an even number.


in order to write a function you must use def

In [1]:
n=3
for i in range(0,n):
    print (2n+1)
    

SyntaxError: invalid syntax (<ipython-input-1-327db5624b9f>, line 3)

def userDefFunction (arg1, arg2, arg3 ...):
    program statement1
    program statement3
    program statement3
    ....
   return;

In [8]:
def int_odd(n):
    my_list=[]
    for i in range (0,n):
        print ("2i+1")
        my_list.append(2i+1)
        retun my_list

SyntaxError: invalid syntax (<ipython-input-8-997b98d4407b>, line 5)

In [6]:
def int_odd(n):
    for i in range (0,n):
        print (2*i+1)
        my_list.append(2*i+1)
        return my_list

In [5]:
int_odd(10)

1


NameError: name 'my_list' is not defined

how to define my list

In [8]:
import math #math is a package

In [9]:
math.pi

3.141592653589793

In [10]:
import math as m

In [11]:
m.pi

3.141592653589793

In [12]:
m.sin(m.pi)

1.2246467991473532e-16

In [13]:
import numpy as np #numerical python

In [16]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

np.sin(x) #applies the sin function to every element in the array 

In [17]:
x=np.arange(0,5)

In [18]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
x+2

array([2, 3, 4, 5, 6])

In [20]:
2*x+1

array([1, 3, 5, 7, 9])

fibbonacci numbers:1,1,2,3,5,8

i
j
i+j
my_list.append[i+j]

how to update
problem is i just reassinged i
i_old=i this saves the old value 
j=i_old+j


In [5]:
i=1
j=0
n=5
print(j)
for x in range (0,n): #x is not used
    i_old = i
    i = j
    j = i_old + j
    print(j)


    

0
1
1
2
3
5


In [6]:
i=0
j=1
n=5

for x in range (0,n): #x is not used
    print(j)
    i_old = i
    i = j
    j = i_old + j
    



1
1
2
3
5


In [9]:
#turn into a function
#create a list of these numbers
#modify so it return numbers below some value (v)

def print_fib(n):
    i=0
    j=1
    n=5
    my_list=[50]
    
for x in range(0,n):
        print(j)
        my_list=[50]
        my_list.append(j)
        i_old = i
        i = j
        j = i_old + j
return my_list


987
1597
2584
4181
6765


SyntaxError: 'return' outside function (<ipython-input-9-c81b8e563c2d>, line 18)

In [12]:
#turn into a function
#create a list of these numbers
#modify so it return numbers below some value (v)
def print_fib(v):
    i=1
    j=0
    
    
    for x in range (0,n): #x is not used
        print(j)
        my_list.append(j)
        i_old = i
        i = j
        j = i_old + j
    return my_list 
        
    

    

In [35]:
print_fib(5)

0


NameError: name 'my_list' is not defined

#turn into a function
#create a list of these numbers
#modify so it return numbers below some value (v)


def print_fib(v):
    i=1
    j=0
    my_list
    
    whilej<v
        print(j)
        my_list.append(j)
        i_old = i
        i = j
        j = i_old + j
    return my_list 