# SciPy Lec 
# After break

In [3]:
import numpy as np

In [4]:
a = np.arange(10000)

In [5]:
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [6]:
%timeit a + 1  

5.65 µs ± 110 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
l = range(10000)
%timeit [i+1 for i in l] 


531 µs ± 4.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [24]:
b.dot(b)

16.0

hmmmm

In [13]:
a = np.array([1, 2, 3, 4])
a + 1


array([2, 3, 4, 5])

In [14]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [16]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [17]:
a * b

array([2., 4., 6., 8.])

In [18]:
j = np.arange(5)

In [19]:
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [20]:
[2**0, 2**1, 2**2, 2**3, 2**4]

[1, 2, 4, 8, 16]

In [21]:
a_j = 2^(3*j) - j

l = range(10000)
%timeit [i+1 for i in l] 

Comparisons

In [25]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [26]:
a > b

array([False, False,  True, False])

In [50]:
a < b

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

Logical operations

In [29]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [30]:
np.logical_and(a,b)

array([ True, False, False, False])

Trancendental functions

In [36]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [37]:
np.log(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [38]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

Shape mismatches

In [39]:
a=np.arange(4)
a+np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

Return to this later?

Transposition

In [42]:
a=np.triu(np.ones((3,3)),1)

In [43]:
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [44]:
a=np.triu(np.ones((3,4)),1)

In [45]:
a

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 0., 1.]])

In [46]:
a=np.triu(np.ones((2,4)),1)

In [47]:
a

array([[0., 1., 1., 1.],
       [0., 0., 1., 1.]])

In [48]:
a=np.triu(np.ones((4,1)),1)

In [49]:
a

array([[0.],
       [0.],
       [0.],
       [0.]])

Gotcha!

In [57]:
help(np.triu)

Help on function triu in module numpy.lib.twodim_base:

triu(m, k=0)
    Upper triangle of an array.
    
    Return a copy of a matrix with the elements below the `k`-th diagonal
    zeroed.
    
    Please refer to the documentation for `tril` for further details.
    
    See Also
    --------
    tril : lower triangle of an array
    
    Examples
    --------
    >>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 1,  2,  3],
           [ 4,  5,  6],
           [ 0,  8,  9],
           [ 0,  0, 12]])



In [58]:
help(np.tril)

Help on function tril in module numpy.lib.twodim_base:

tril(m, k=0)
    Lower triangle of an array.
    
    Return a copy of an array with elements above the `k`-th diagonal zeroed.
    
    Parameters
    ----------
    m : array_like, shape (M, N)
        Input array.
    k : int, optional
        Diagonal above which to zero elements.  `k = 0` (the default) is the
        main diagonal, `k < 0` is below it and `k > 0` is above.
    
    Returns
    -------
    tril : ndarray, shape (M, N)
        Lower triangle of `m`, of same shape and data-type as `m`.
    
    See Also
    --------
    triu : same thing, only for the upper triangle
    
    Examples
    --------
    >>> np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
    array([[ 0,  0,  0],
           [ 4,  0,  0],
           [ 7,  8,  0],
           [10, 11, 12]])



In [59]:
help(np.allclose.)

SyntaxError: invalid syntax (<ipython-input-59-b7895f46a2b4>, line 1)

# 1.3.2.2 Basic Reductions

Computing sums

In [60]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [61]:
x.sum()

10

Sum by rows and by columns

In [63]:
x = np.array([[1, 1], [2, 2]])
x 

array([[1, 1],
       [2, 2]])

In [64]:
x.sum(axis=0) #sum of (1+2),(1+2)

array([3, 3])

In [65]:
x[:, 0].sum(), x[:, 1].sum()


(3, 3)

In [66]:
x.sum(axis=1) #sum of (1+1),(2+2)

array([2, 4])

In [67]:
x[0, :].sum(), x[1, :].sum()


(2, 4)

In [68]:
x[0, :].sum(), x[1, :].sum()


(2, 4)

Other reductions

In [76]:
x = np.array([12, 25, 156])
x.min()

12

In [77]:
x.max()

156

In [78]:
x.argmin()

0

In [79]:
x.argmax()

2

In [80]:
np.all([True,True,False])

False

In [81]:
np.any([True,True,False])

True

Logical operations can be used for array comparison

In [83]:
a = np.zeros((100, 100))
np.any(a = 0)

False

In [84]:
np.all (a==a)

True

In [86]:
a= np.array([1,2,3,2])
b= np.array([2,2,3,2])
c= np.array([6,4,4,5])
((a<=b)& (b<=c)).all()

True

Statistics

In [88]:
x=np.array([1,2,3,1])
y=np.array ([[1,2,3],[5,6,1]])
x.mean()

1.75