## Make a function that prints odd numbers

In [25]:
list1 = [10, 11, 12, 13, 14, 15, 21, 33, 38, 40, 45, 66, 93] 
  
def num_odd(x):
    for num in x: 
        if num % 2 != 0: 
           print(num, end = " ") 
num_odd(list1)

11 13 15 21 33 45 93 

class example

In [20]:
def int_odd(n):
    my_list =[]
    for i in range (0, n):
        print(2 * i + 1)
        my_list.append(2 * i + 1)
    return my_list
int_odd(9)

1
3
5
7
9
11
13
15
17


[1, 3, 5, 7, 9, 11, 13, 15, 17]

In [21]:
int_odd(4)

1
3
5
7


[1, 3, 5, 7]

In [22]:
int_odd(10)

1
3
5
7
9
11
13
15
17
19


[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

Practice python #1

In [12]:
name = input("What is your name: ")

What is your name:  Blerg


In [ ]:
print("Your name is " + name)

In [15]:
age = int(input("Enter your age: "))

Enter your age:  17


In [28]:
year = str(2119 - age)
print(year)

2102


In [30]:
print(name + " you will turn 100 in year: " + year)

Blerg you will turn 100 in year: 2102


## Packages

In [32]:
import math # math is a package
#packages give predefine functions

In [33]:
math.pi

3.141592653589793

In [34]:
math.sin(math.pi)

1.2246467991473532e-16

In [35]:
#using short hand
import math as m

In [36]:
m.sin(m.pi)

1.2246467991473532e-16

In [39]:
 import numpy as np #numpy means numerical python

In [42]:
x = np.arange(0,5)

In [43]:
np.sin(x) #applies the sin function to every element in the array 
            #also know as broadcasting

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [44]:
x + 2

array([2, 3, 4, 5, 6])

In [45]:
2*x+1

array([1, 3, 5, 7, 9])