In [86]:
def odd(n):
    for num in range(n) if (num % 2 == 1)
        print (num)

SyntaxError: invalid syntax (<ipython-input-86-8d36b0e254f0>, line 2)

In [16]:
odd = [num for num in range(20) if num % 2 == 1] 

In [18]:
for i in range(20):
    print (odd)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [74]:
n=3

In [69]:
for i in range(0,n):
    print(2*i+1)

1
3
5


In [77]:
def int_odd(n):
    my_list=[]
    for i in range(0,n):
        print(2*i+1)
        my_list.append(2*i+1)
    return my_list

In [79]:
print(int_odd(5))

1
3
5
7
9
[1, 3, 5, 7, 9]


# Practicepython.org

In [19]:
x = range(2,11)

In [23]:
for elem in x:
    print (elem)

2
3
4
5
6
7
8
9
10


In [24]:
num = input("Give me a number: ")

Give me a number: 12


In [29]:
num_divi = (elem for elem in num if num % 2 == 0)

In [30]:
print (num_divi)

<generator object <genexpr> at 0x1117cc9a8>


In [32]:
num = int(input("Give me a number: "))

Give me a number: 12


In [35]:
div_set=[]

In [39]:
for i in range(1,num+1):
    if num%i==0:
        div_set.append(num)
        print(div_set)
        print()

[12, 12, 12, 12, 12, 12, 12]

[12, 12, 12, 12, 12, 12, 12, 12]

[12, 12, 12, 12, 12, 12, 12, 12, 12]

[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]

[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]

[12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]



In [41]:
num = int(input("Please enter a number: "))

Please enter a number: 15


In [45]:
divisorList=[]

In [46]:
while num<=x:
    if x%num==0:
        divisotrList.append(num)
        num+=1
        
print (str(x) +"has" +str(len(divisorList))+"divisors")
print (divisorList)

TypeError: '<=' not supported between instances of 'int' and 'range'

# Notes

In [87]:
import math #math is a package

In [88]:
math.pi

3.141592653589793

In [89]:
math.sin(math.pi)

1.2246467991473532e-16

In [90]:
import math as m

In [91]:
m.pi

3.141592653589793

In [92]:
import numpy as np #numerial python

In [94]:
x = np.arange(0,5) #this creates a numpy array

In [96]:
x

array([0, 1, 2, 3, 4])

In [95]:
np.sin(x) #applies the sin function to every element in array, called broadcasting

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [97]:
x +2

array([2, 3, 4, 5, 6])

In [98]:
2*x+1

array([1, 3, 5, 7, 9])

# Problem

Fibonacci Numbers

adds the previous two numbers together

1, 1, 2, 3, 5, 8, 13 ... etc.

two variables: i and j
my_list.append[i+j] --> 
i = 2, j = 3, i + j = 5
i = 3, j = 5, i + j = 8
have to uptake previous j as i, and i+j as new j
if we change new i, new j won't be correct from reassigning numbers.
    i_old = i to save old value
        i_old = i
        i = j
        j = i_old + j
Start i = 0, j = 1
for range (0,n):
        i_old = i
        i = j
        j = i_old + j

In [110]:
n=5

i = 0
j = 1

for x in range(0,n):
    print(j)
    i_old = i
    i = j
    j = i_old+j


1
1
2
3
5


In [115]:
del j

In [118]:
#Now turn into a function


def fib(n):
    i = 0
    j = 1
    for x in range(0,n):
        print(j)
        i_old = i
        i = j
        j = i_old+j


In [120]:
fib(10)

1
1
2
3
5
8
13
21
34
55


In [129]:
#Now create a list of these numbers which are returned
# def int_odd(n):
#     my_list=[]
#     for i in range(0,n):
#         print(2*i+1)
#         my_list.append(2*i+1)
#     return my_list

def fib(n):
    my_list=[1,]
    i = 0
    j = 1
    for x in range(0,n):
        print(j)
        i_old = i
        i = j
        j = i_old+j
        my_list.append(i_old+j)
    return my_list


In [130]:
fib(5)

1
1
2
3
5


[1, 1, 3, 4, 7, 11]

In [131]:
fib(10)

1
1
2
3
5
8
13
21
34
55


[1, 1, 3, 4, 7, 11, 18, 29, 47, 76, 123]

In [143]:
#Now modify to print out all Fib #'s under a certain value

def fib(n):
    my_list=[1,]
    i = 0
    j = 1
    for x in range(0,n):
        while j < 1000:
            print(j)
            i_old = i
            i = j
            j = i_old+j
            my_list.append(i_old+j)
        return my_list

In [144]:
fib(100)

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


[1, 1, 3, 4, 7, 11, 18, 29, 47, 76, 123, 199, 322, 521, 843, 1364, 2207]

In [149]:
#Another way to do it:

def fib(v):
    my_list=[1,]
    i = 0
    j = 1
    #for x in range(0,n):
    while j < v:
        print(j)
        i_old = i
        i = j
        j = i_old+j
        my_list.append(i_old+j)
    return my_list

In [150]:
fib(40)

1
1
2
3
5
8
13
21
34


[1, 1, 3, 4, 7, 11, 18, 29, 47, 76]

# Practice Python 1, 2, 9, 25

## Practic 9

In [152]:
import random as rd

In [153]:
a = rd.randint(2,6)

In [154]:
a

4

In [151]:
num = int(input("Guess a number from 1 - 9: "))

Give me a number from 1 - 9: 5


In [155]:
x = rd.randint(1,9)

In [156]:
for x:
    if x == num:
        print ("you guessed it!")
    else:
        print ("better luck next time")

SyntaxError: invalid syntax (<ipython-input-156-309963b001a0>, line 1)

In [176]:
number = rd.randint(1,9)
guess = None
another = None
TRY = 0
running = True

print("Alright...")

Alright...


In [177]:
while running:
    guess = int(input("Guess a number from 1 - 9: "))
    if guess < number:
        print("Wrong, too low.")
    elif guess > number:
        print("Wrong too high.")
#     elif guess.lower() == "exit":
#         print ("Better luck next time.")
    elif guess == number:
        #print("Impressive, only %s tries" % str(TRY))
        if TRY < 2:
            print("Impressive, only %s tries." %str(TRY))
        elif TRY > 2 and TRY < 10:
            print ("Pretty good, %s tries" %str(TRY))
        elif TRY > 10:
            print("Bad, %s tries." % str(TRY))
        running = False
    TRY += 1

Guess a number from 1 - 9: 9
Wrong too high.
Guess a number from 1 - 9: 1
Wrong, too low.
Guess a number from 1 - 9: 8
Wrong too high.
Guess a number from 1 - 9: 2
Wrong, too low.
Guess a number from 1 - 9: 7
Wrong too high.
Guess a number from 1 - 9: 3
Wrong, too low.
Guess a number from 1 - 9: 6
Pretty good, 6 tries


## Practice 25

Program has to pick a number between 0-100 and the user says is it's right or wrong and how many tries when it gets it. User will say "too high, too low, or correct.

In [ ]:
while running:
    guess = int(input("Guess a number from 1 - 9: "))
    if guess < number:
        print("Wrong, too low.")
    elif guess > number:
        print("Wrong too high.")
#     elif guess.lower() == "exit":
#         print ("Better luck next time.")
    elif guess == number:
        #print("Impressive, only %s tries" % str(TRY))
        if TRY < 2:
            print("Impressive, only %s tries." %str(TRY))
        elif TRY > 2 and TRY < 10:
            print ("Pretty good, %s tries" %str(TRY))
        elif TRY > 10:
            print("Bad, %s tries." % str(TRY))
        running = False
    TRY += 1

In [179]:
while running:
    guess = 50
    check = input("Did I get it? High? Low?: ")
    if check = "yes":
        print("Yes! only %s tries." %str(TRY))
    if check = "High":
        new_guess = guess - 1
    if check = "Low":
        new_guess = guess + 1

SyntaxError: invalid syntax (<ipython-input-179-b6fb611dee8a>, line 4)

In [182]:
NUMBER = rd.randint(0,100)
TRY = 0
RUNNING = True
ANSWER = None

In [188]:
while RUNNING:
    print("Is it %s?" % str(NUMBER))
    ANSWER = input()
    if "no" in ANSWER.lower() and "lower" in ANSWER.lower():
        NUMBER -= rd.randit(1,4)
    elif "no" in ANSWER.lower() and "higher" in ANSWER.lower():
        NUMBER += rd.randit(1,4)
    elif ANSWER.lower() =="no":
        print("Higher or lower?")
        ANSWER = input()
        if ANSWER.lower() == "higher":
            NUMBER += rd.randint(1,4)
        elif ANSWER.lower() == "lower":
            NUMBER -= rd.randint(1,4)
    elif ANSWER.lower() == "yes":
        if TRY < 2:
            print("Yes! It only took me %s try!" % str(TRY))
        elif TRY < 2 and TRY < 10:
            print ("Pretty good for a robot, %s tries." % str(TRY))
        else:
            print("That's so bad, %s tries." % str(TRY))
        RUNNING = False
    TRY += 1

print("Thanks for the game!")

Is it 3?
no
Higher or lower?
higher
Is it 4?
no
Higher or lower?
higher
Is it 7?
no
Higher or lower?
lower
Is it 3?
no
Higher or lower?
higher
Is it 7?
no
Higher or lower?
lower
Is it 5?
yes
That's so bad, 5 tries.
Thanks for the game!
